### ISSUE TITLE
Table of contents not compiled

### ISSUE THREAD

**Issue by mrdaliri** [draldric/uAlberta-Thesis-LaTeX-Template#3]
Hi @draldric,
Thanks for open-sourcing your template. It's quite helpful!

I'm having issues compiling `ualberta.tex` on a freshly-cloned repo with PdfLaTeX on macOS. My TeXStudio says there is something wrong with ualberta.toc (table of contents) file. I have installed almost all essential TeX packages with MikTeX.

Do you happen to have any thoughts?

![image](https://user-images.githubusercontent.com/4965944/108672171-d90b8e00-749e-11eb-8669-39ba2bc0afc4.png)

Thanks :)

**Comment by draldric** [comment]
Can you please share the log file?
I can be quite hard to determine what has gone wrong without seeing the full error.

**Comment by draldric** [comment]
@mrdaliri please note: If no further details are provided, this issue will be closed on March 1, 2020, under the assumption that the issue has been resolved.

**Comment by draldric** [comment]
This issue is closed due to lack of further details, and failure to reproduce the issue.

**Comment by mrdaliri** [comment]
Hi @draldric,
Sorry I was away from this project for a couple weeks.
Here is the log file (ualberta.log): https://pastebin.com/d2NeXpaB
Please let me know if you need any other information.
Thanks for taking the time to look into this issue.

**Comment by draldric** [comment]
@mrdaliri 

I can only think of a couple reasons this might not be working...
1. Try to delete all the Tex generated files e.g. .log, .toc, .aux,...etc

Then you have to run latex, bibtex, latex, latex if you have any errors on the last run then this didn't work.

2. Try to make sure you have a completely up to date installation of latex then proceed with step 1

3. If neither of these work, the template is available on overleaf as a free cloud based solution.

**Comment by mrdaliri** [comment]
Thanks @draldric. Upgraded to latest version (2020) and problem solved.
