### ISSUE TITLE
Reference index problem

### ISSUE THREAD

**Issue by BinYang24** [draldric/uAlberta-Thesis-LaTeX-Template#4]
Hi draldric thank you for your template!
I met a problem when adding reference into reference.bib
when I add a new article into it, it appears index [0]
I am not sure how to fix that.
 
![1618367144(1)](https://user-images.githubusercontent.com/61919492/114645360-8d9f8000-9c96-11eb-98bc-cab95bb5d926.png)

**Comment by draldric** [comment]
Hello @BinYang24 ,
I'm glad my thesis template has helped you.

To get around this you need to delete the generated files from LaTeX... I.e. *.aux, *.bbl,... etc

This happens when you add new references to the bib file.

**Comment by BinYang24** [comment]
> Hello @BinYang24 ,
> I'm glad my thesis template has helped you.
> 
> To get around this you need to delete the generated files from LaTeX... I.e. *.aux, *.bbl,... etc
> 
> This happens when you add new references to the bib file.

**Comment by BinYang24** [comment]
> Hello @BinYang24 ,
> I'm glad my thesis template has helped you.
> 
> To get around this you need to delete the generated files from LaTeX... I.e. *.aux, *.bbl,... etc
> 
> This happens when you add new references to the bib file.

Thank you so much for you help.
But I am still confused.
I use your template on overleaf, I am not sure where is the generated files...
![1618370363(1)](https://user-images.githubusercontent.com/61919492/114649576-fe966600-9c9d-11eb-9f36-e11ada0fb8bf.png)

**Comment by draldric** [comment]
![image](https://user-images.githubusercontent.com/16022748/114650268-2df9a280-9c9f-11eb-8311-8c3efd1f5d9d.png)

**Comment by BinYang24** [comment]
Thank you so much!
I solve the problem
Thank you again for your template!
