### ISSUE TITLE
Alphabetical citations

### ISSUE THREAD

**Issue by eimontecast** [draldric/uAlberta-Thesis-LaTeX-Template#5]
Hello,

I have been using your template and I have a problem. My citations using printbibliography are not in alphabetical order. I believe they are appearing in the order they were cited. Is there a way to fix this?

**Comment by draldric** [comment]
Hello @eimontecast ,

This was chosen on purpose, as the main citation style within the sciences(engineering) is numeric in the order of appearance.

If you would like to change this you can edit includePackages.tex:

To change the appearance of the refences in the reference section you can change the `style` option with:
<img src="https://user-images.githubusercontent.com/16022748/122845483-16ebb800-d2c1-11eb-8bf9-a21792834f39.png" alt="style options" width="50%"/>

To change the appearance of the citations you you can change `citestyle` with:<img src="https://user-images.githubusercontent.com/16022748/122845214-667db400-d2c0-11eb-9c2b-a0232bede8d9.png" alt="citestyle options" width="70%"/>

**Note**: Changing the style of the bibliography or the bib file itself will require the temporary files aux, log, etc... to be deleted and the project recompiled.

**Comment by draldric** [comment]
@eimontecast please note: If no further details are provided, this issue will be closed on June 28, 2021, under the assumption that the issue has been resolved.
