### ISSUE TITLE
Converting problem (when convert pdf to pdf/a)

### ISSUE THREAD

**Issue by BinYang24** [draldric/uAlberta-Thesis-LaTeX-Template#6]
Hi 
When I download the pdf from the overleaf and try to convert it to pdf/a file, a problem occurs:
![problem](https://user-images.githubusercontent.com/61919492/133706670-5b2e189d-9824-450c-8595-2a1301bbd161.png)
Do you know how to fix it?

Thanks!
Bin

**Comment by BinYang24** [comment]
Sorry I saw the source code
Once the pdf is downloaded, it is in the version of pdf/a and no any transformation is needed, am I right?

Regards,
Bin

**Comment by draldric** [comment]
Yes, that is correct.

The package is already included that creates the pdfa you should edit the
ualberta.xmpdata with the correct info for your thesis though.

Regards,
